---
repos:
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: "v2.2.1"
    hooks:
      - id: prettier
        args: ["--print-width=135"]
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.4.0
    hooks:
      - id: check-case-conflict
      - id: check-executables-have-shebangs
      - id: check-merge-conflict
      - id: check-yaml
        args: ["--allow-multiple-documents"]
      - id: end-of-file-fixer
      - id: file-contents-sorter
        args: ["--ignore-case", "--unique"]
        files: '^\.gitignore$'
      - id: mixed-line-ending
        args: ["--fix=lf"]
      - id: trailing-whitespace
  - repo: https://github.com/Lucas-C/pre-commit-hooks
    rev: v1.1.9
    hooks:
      - id: remove-tabs
        exclude_types: [makefile, binary]
  - repo: https://github.com/adrienverge/yamllint.git
    rev: v1.26.0
    hooks:
      - id: yamllint
  - repo: https://github.com/danielhoherd/pre-commit-hooks
    rev: bd325c947efcba13c03b4f4c93d882f2f83ed6ff
    hooks:
      - id: remove-en-dashes
      - id: remove-unicode-non-breaking-spaces
      - id: remove-unicode-zero-width-non-breaking-spaces
      - id: remove-unicode-zero-width-space
